apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: 2048-app
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
        - name: 2048-app-container
          image: mamir32825/2048:latest  # Use your actual Docker image name and tag
          ports:
            - containerPort: 3000  # The port your app is listening on

---
apiVersion: v1
kind: Service
metadata:
  name: 2048-app-service
spec:
  selector:
    app: 2048-app
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the service within the cluster
      targetPort: 3000  # The port your app is listening on inside the pod
  type: LoadBalancer
